### ISSUE TITLE
How to "Add to Home" for desktop browser

### ISSUE THREAD

**Issue by ccpster** [nishantpainter/personal-kanban#3]
Hi,
Thanks for develop this app, been looking something like this for long time.

May be I am just being ignorance, but in your Readme stated that one can use 'Add to Home' in browser. But I can not find such thing anywhere in my browser. I checked with my firefox as well as google chrome both do seems to have such feature.

Could you share more on how to achieve Offline use?

Thanks.

**Comment by nishantpainter** [comment]
You can follow this link : https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DDesktop&hl=en&oco=0

:smile:

**Comment by ccpster** [comment]
Hi,

Thanks for the information, it help me better understand what is "Add to home" feature.

However, it is not working for my chrome browser still. I search internet around a follow a [suggestion](https://developers.google.com/web/tools/chrome-devtools/progressive-web-apps) to see what is wrong in my browser and following screenshot is what I found, I am not a web developer so I don't know exactly where is wrong but I suspect because the "icon sizes" should be only 1 not 4 that might trigger browser now working as expected.

![image](https://user-images.githubusercontent.com/22875424/102399386-8ef1c200-3fae-11eb-8268-c87eb17c0360.png)

**Comment by nishantpainter** [comment]
Thanks for the update. I have fixed the favicon size in manifest and also updated the service worker file. You will be now able to add it to home screen. :)

**Comment by ccpster** [comment]
Hi,

Just want to confirm that I saw correct service working now.

Thanks,

Ping.
