### ISSUE TITLE
Document how to install and start

### ISSUE THREAD

**Issue by tomschr** [nishantpainter/personal-kanban#5]
# Situation

Thank you for this project!  :+1: 
At the moment, the README file doesn't explain how to install and start it. At least, it's not clear to me. :wink:  Especially for users which doesn't know TypeScript it could be helpful to have some basic steps.

# Proposal

I would love to see some short steps which are needed to install the project on your computer and how to start it.
Thanks!

**Comment by dmpop** [comment]
These steps worked for me on a Ubuntu 20.04-based machine:

```
git clone https://github.com/nishantpainter/personal-kanban.git
cd personal-kanban
yarn install
yarn build
sudo npm install -g serve
serve -s build
```

**Comment by nishantpainter** [comment]
Thanks for the proposal @tomschr for the update @dmpop. I have updated the readme with same. Thanks :+1:
