### ISSUE TITLE
如何在chrome中使用呢？

### ISSUE THREAD

**Issue by jwc19890114** [nishantpainter/personal-kanban#6]
我看到介绍里面可以使用edge在应用中安装，chrome是否有这样的功能呢，直接放在首页

**Comment by nishantpainter** [comment]
是的，您已经在Chrome浏览器中添加了主页选项。请检查屏幕截图以获取更多详细信息，或点击以下链接：

https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DDesktop&hl=en&oco=0

![Add to home](https://user-images.githubusercontent.com/27288169/102684154-44fe1b80-41fc-11eb-8294-de464c3627dd.png)
