### ISSUE TITLE
transfer of board to another PC

### ISSUE THREAD

**Issue by kris222** [nishantpainter/personal-kanban#8]
Hi. 
I found your app. it is great- simple and functional.
And I have a question: 
Is there any way to transfer the board created on one machine to other (or one web browser to other) ? is there any folder on disc which stores data, I can transfer?
Regards,
kris

**Comment by nishantpainter** [comment]
Hello, Glad that you like the application.

For now there is now option within the application to transfer the column data onto another machine. But you can still do it manually. The application store all it's data in browser local storage.

You can navigate to browser->local storage where you will find `columns` key and it's value. You can copy the value and then paste that within the machine you want to transfer it to with the same key `columns`. This will do. 

Thanks.

**Comment by kris222** [comment]
Thanks,
It solves my problem.
Regards,
kris
